'use client'

import { useMemo, useState, useTransition } from 'react'
import { processImportRowsAction } from '@/app/actions/importActions'
import { importFieldsForMode, inferImportMapping, type ImportMode } from '@/lib/import-mapping'

type Row = Record<string,string>
type Result = { message:string; warnings:string[]; errors:string[]; summary:{products:number;markets:number;competitorUrls:number;readyForMonitoring:number} }
type PreviewResponse = { headers:string[]; preview:Row[]; rows?:Row[]; format:'CSV'|'XLSX'; error?:string }

function templateHeaders(mode:ImportMode){ return importFieldsForMode(mode).map((field)=>field.label) }
function filenameFor(mode:ImportMode){ return mode==='products'?'prysight-producten-template.csv':mode==='competitors'?'prysight-concurrenten-template.csv':'prysight-volledige-import-template.csv' }

export function ImportWizard(){
  const [step,setStep]=useState(1),[mode,setMode]=useState<ImportMode>('products'),[filename,setFilename]=useState(''),[format,setFormat]=useState<'CSV'|'XLSX'>('CSV')
  const [headers,setHeaders]=useState<string[]>([]),[rows,setRows]=useState<Row[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[result,setResult]=useState<Result|null>(null),[uploadError,setUploadError]=useState<string|null>(null)
  const [isPending,startTransition]=useTransition()
  const fields=useMemo(()=>importFieldsForMode(mode),[mode])
  const mappedRows=useMemo(()=>rows.map((row)=>Object.fromEntries(Object.entries(mapping).filter(([,column])=>Boolean(column)).map(([target,column])=>[target,row[column]??'']))),[rows,mapping])
  const preview=mappedRows.slice(0,5), autoMapped=fields.filter((field)=>Boolean(mapping[field.key])).length
  const warnings=useMemo(()=>{const list:string[]=[];if(!mapping.articleNumber)list.push('Artikelnummer/SKU ontbreekt.');if(mode!=='competitors'&&!mapping.productName)list.push('Productnaam ontbreekt.');if(!mapping.country)list.push('Land ontbreekt, NL wordt als standaard gebruikt.');if(mode!=='products'&&!mapping.competitorUrl)list.push('Concurrent URL ontbreekt.');if(mode!=='products'&&!mapping.competitorName)list.push('Concurrentnaam ontbreekt.');return list},[mapping,mode])

  async function upload(file:File){setUploadError(null);const body=new FormData();body.append('file',file);const response=await fetch('/api/import',{method:'POST',body});const payload=await response.json() as PreviewResponse;if(!response.ok||payload.error){setUploadError(payload.error??'Bestand kon niet worden gelezen.');return}setFilename(file.name);setFormat(payload.format);setHeaders(payload.headers);setRows(payload.rows??payload.preview);setMapping(inferImportMapping(payload.headers));setResult(null);setStep(2)}
  function downloadTemplate(){const csv=`${templateHeaders(mode).join(';')}\n`;const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filenameFor(mode);a.click();URL.revokeObjectURL(url)}
  function run(){setStep(4);setResult(null);startTransition(async()=>setResult(await processImportRowsAction({filename,format,mode,mapping,rows:mappedRows})))}

  return <div className="strong-panel overflow-hidden">
    <div className="border-b border-[var(--border)] px-5 py-4"><div className="flex flex-wrap gap-2 text-[10px] font-semibold text-[#8a93a5]">{['Bron','Kolommen','Controle','Resultaat'].map((label,index)=><span key={label} className={step>=index+1?'text-[#202536]':''}>{index+1}. {label}{index<3?'  ›':''}</span>)}</div></div>
    <div className="p-5 sm:p-6">
      {step===1?<div className="space-y-5"><div><h2 className="text-[16px] font-semibold">Wat wil je importeren?</h2><p className="mt-1 text-[11px] text-[#8a93a5]">PrySight herkent product- en pricingvelden automatisch. Alleen uitzonderingen hoef je te corrigeren.</p></div><div className="grid gap-3 md:grid-cols-3">{([['products','Producten','Productdata, identifiers, kostprijs en marges.'],['competitors','Concurrenten','Concurrenten en product-URL’s koppelen.'],['combined','Volledige import','Product- en concurrentiedata in één import.']] as const).map(([value,title,description])=><button type="button" key={value} onClick={()=>setMode(value)} className={`rounded-[14px] border p-4 text-left ${mode===value?'border-[var(--blue)] bg-[var(--blue-soft)]':'border-[var(--border)] bg-white'}`}><p className="text-[12px] font-semibold">{title}</p><p className="mt-1 text-[10px] leading-5 text-[#8a93a5]">{description}</p></button>)}</div><div className="rounded-[14px] border border-dashed border-[#c9ced8] bg-[#fafbfc] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[12px] font-semibold">CSV of Excel</p><p className="mt-1 text-[10px] text-[#8a93a5]">SKU, EAN, GTIN, MPN, merk, model, verpakking, kostprijs, marge en pricingmodus worden automatisch herkend.</p></div><button type="button" onClick={downloadTemplate} className="secondary-action">Voorbeeldtemplate</button></div><input type="file" accept=".csv,.xlsx" className="mt-4 block w-full rounded-xl border border-[var(--border)] bg-white p-3 text-[11px]" onChange={(event)=>{const file=event.target.files?.[0];if(file)void upload(file)}}/>{uploadError?<p className="mt-2 text-[11px] text-rose-700">{uploadError}</p>:null}</div></div>:null}
      {step===2?<div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-[16px] font-semibold">Kolommen controleren</h2><p className="mt-1 text-[11px] text-[#8a93a5]">{filename}, {rows.length} regels. {autoMapped} van {fields.length} relevante velden automatisch herkend.</p></div><div className="flex gap-2"><button className="secondary-action" onClick={()=>setStep(1)}>Ander bestand</button><button className="primary-action" onClick={()=>setStep(3)}>Preview</button></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{fields.map((field)=><label key={field.key} className="space-y-1.5 text-[11px]"><span className="font-semibold text-[#697386]">{field.label}</span><select className="toolbar-control w-full" value={mapping[field.key]??''} onChange={(event)=>setMapping((current)=>({...current,[field.key]:event.target.value}))}><option value="">Niet gekoppeld</option>{headers.map((header)=><option key={header} value={header}>{header}</option>)}</select></label>)}</div></div>:null}
      {step===3?<div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-[16px] font-semibold">Preview en validatie</h2><p className="mt-1 text-[11px] text-[#8a93a5]">Na bevestigen worden producten opgeslagen; discovery draait daarna server-side in batches.</p></div><div className="flex gap-2"><button className="secondary-action" onClick={()=>setStep(2)}>Terug</button><button className="primary-action" onClick={run}>Bevestigen en importeren</button></div></div><div className={`rounded-[14px] p-4 text-[11px] ${warnings.length?'bg-[var(--amber-soft)] text-[var(--amber)]':'bg-[var(--green-soft)] text-[var(--green)]'}`}><p className="font-semibold">{warnings.length?`${warnings.length} aandachtspunten`:'Mapping ziet er compleet uit'}</p>{warnings.length?<ul className="mt-2 list-disc pl-5">{warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul>:null}</div><div className="overflow-x-auto rounded-[14px] border border-[var(--border)]"><table className="min-w-full text-[10px]"><thead className="bg-[#f7f8fa]"><tr>{Object.keys(preview[0]??{}).map((key)=><th className="px-3 py-2 text-left" key={key}>{key}</th>)}</tr></thead><tbody>{preview.map((row,index)=><tr key={index} className="border-t border-[var(--border)]">{Object.entries(row).map(([key,value])=><td key={key} className="whitespace-nowrap px-3 py-2">{value||'—'}</td>)}</tr>)}</tbody></table></div></div>:null}
      {step===4?<div className="space-y-5"><h2 className="text-[16px] font-semibold">{isPending?'Import wordt verwerkt…':result?.errors.length?'Import met aandachtspunten afgerond':'Import afgerond'}</h2>{isPending?<p className="text-[11px] text-[#8a93a5]">Producten en pricingvelden worden verwerkt.</p>:result?<><p className="text-[11px] text-[#697386]">{result.message}</p><div className="grid gap-3 sm:grid-cols-4">{[['Producten',result.summary.products],['Markten',result.summary.markets],['Concurrent URLs',result.summary.competitorUrls],['Monitoring klaar',result.summary.readyForMonitoring]].map(([label,value])=><div key={String(label)} className="rounded-[12px] bg-[#f6f8fb] p-4"><p className="text-[10px] text-[#8a93a5]">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>{result.errors.length?<ul className="text-[11px] text-rose-700">{result.errors.slice(0,20).map((error)=><li key={error}>{error}</li>)}</ul>:null}<button className="secondary-action" onClick={()=>{setStep(1);setResult(null)}}>Nieuwe import</button></>:null}</div>:null}
    </div>
  </div>
}
