import Link from 'next/link'
import { MatchStatus } from '@/generated/prisma/client'
import { requireAuthenticatedUser } from '@/lib/authz'
import { getDashboardSnapshot, type DashboardSnapshot } from '@/lib/dashboard'
import { formatCurrency, formatNumber } from '@/lib/format'
import { profileStep } from '@/lib/performance-profile'

export const dynamic = 'force-dynamic'

function readParam(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value }
const emptySnapshot: DashboardSnapshot = { filterOptions: { countries: [], productGroups: [], competitors: [] }, metrics: [], kpis: { monitoredProducts: 0, activeOffers: 0, validMatches: 0, reviewMatches: 0, withoutCompetitorPrice: 0, engelsLowest: 0, engelsHigher: 0, averagePriceIndex: null, failedChecks: 0, staleData: 0 }, biggestIncreases: [], biggestDecreases: [], failedChecks: [], staleOffers: [] }

function KpiCard({ label, value, helper, href, tone }: { label: string; value: string; helper: string; href: string; tone: 'red'|'amber'|'green'|'blue' }) {
  const colors = { red: ['#ee6769','#fff0f0'], amber: ['#f2a51a','#fff6e4'], green: ['#29a56f','#ecf8f2'], blue: ['#4f86e8','#edf4ff'] }[tone]
  return <Link href={href} prefetch className="relative overflow-hidden rounded-[10px] border border-[#e2e7ee] bg-white p-5 pl-6 shadow-[0_2px_8px_rgba(31,49,77,.04)] transition hover:-translate-y-px hover:shadow-[0_6px_16px_rgba(31,49,77,.065)]"><span className="absolute inset-y-0 left-0 w-[3px]" style={{background:colors[0]}}/><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[9px] text-[20px] font-bold" style={{background:colors[1],color:colors[0]}}>•</div><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold text-[#2d3b51]">{label}</p><p className="mt-1 text-[29px] font-bold tracking-[-.04em] text-[#17233a]">{value}</p><p className="mt-1 text-[10px] text-[#7b889a]">{helper}</p><span className="mt-3 inline-flex text-[10px] font-semibold text-[#3977db]">Bekijk overzicht →</span></div></div></Link>
}

export default async function OneGlanceDashboardPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const actor = await requireAuthenticatedUser()
  const params = await searchParams
  const filters: { countryId?: string; productGroupId?: string; competitorId?: string; matchStatus?: MatchStatus|'' } = { countryId: readParam(params.land), productGroupId: readParam(params.productgroep), competitorId: readParam(params.concurrent), matchStatus: (readParam(params.matchstatus) as MatchStatus|undefined) ?? '' }
  let snapshot = emptySnapshot
  let databaseAvailable = true
  try { snapshot = await profileStep('/dashboard','snapshot',()=>getDashboardSnapshot(filters,actor.companyId),{companyId:actor.companyId},350) } catch (error) { console.error('Dashboard database query failed',error); databaseAvailable = false }

  const coverage = snapshot.kpis.monitoredProducts > 0 ? Math.min(100, Math.round(snapshot.kpis.validMatches / snapshot.kpis.monitoredProducts * 100)) : 0
  const selectedCountryName = filters.countryId ? snapshot.filterOptions.countries.find(c=>c.id===filters.countryId)?.name : null
  const movements = [...snapshot.biggestDecreases.slice(0,3), ...snapshot.biggestIncreases.slice(0,3)]
  const totalDistribution = Math.max(snapshot.kpis.engelsLowest + snapshot.kpis.engelsHigher + snapshot.kpis.withoutCompetitorPrice, 1)
  const lowPct = Math.round(snapshot.kpis.engelsLowest / totalDistribution * 100)
  const highPct = Math.round(snapshot.kpis.engelsHigher / totalDistribution * 100)
  const missingPct = Math.max(0, 100 - lowPct - highPct)
  const now = new Date()
  const greeting = now.getHours() < 12 ? 'Goedemorgen' : now.getHours() < 18 ? 'Goedemiddag' : 'Goedenavond'
  const dateLabel = new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now)
  const attentionRows = movements.slice(0,5)
  const maxMove = Math.max(...movements.map(m=>Math.abs(m.latestPrice)),1)

  return <div className="space-y-5">
    {!databaseAvailable && <div className="rounded-[9px] border border-[#f1cfd0] bg-[#fff0f0] p-4 text-[12px] font-semibold text-[#c64f52]">Databaseverbinding mislukt. Prysight toont bewust geen vervangende data.</div>}

    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-[30px] font-bold tracking-[-.04em] text-[#17233a]">{greeting}, {actor.name || 'Prysight gebruiker'}</h1><p className="mt-1 text-[12px] text-[#718096]">Hier is het actuele overzicht van je prijspositie en marktontwikkelingen{selectedCountryName ? ` voor ${selectedCountryName}` : ''}.</p></div><div className="flex flex-wrap items-center gap-3"><div className="rounded-[9px] border border-[#e2e7ee] bg-white px-4 py-3 shadow-[0_2px_8px_rgba(31,49,77,.035)]"><p className="text-[10px] font-semibold capitalize text-[#2f3d53]">{dateLabel}</p><p className="mt-1 text-[9px] text-[#8b98aa]">Actuele monitoringdata</p></div><form className="flex gap-2"><select name="land" defaultValue={filters.countryId} className="toolbar-control min-w-[165px]"><option value="">Alle landen</option>{snapshot.filterOptions.countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary-action">Toepassen</button></form></div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Producten te duur" value={formatNumber(snapshot.kpis.engelsHigher)} helper="Staan boven de gemeten marktprijs" href="/producten" tone="red" /><KpiCard label="Ontbrekende prijsdata" value={formatNumber(snapshot.kpis.withoutCompetitorPrice)} helper="Geen actuele concurrentieprijs" href="/producten" tone="amber" /><KpiCard label="Monitoring gezond" value={`${coverage}%`} helper="Bevestigde prijsdekking" href="/monitoring" tone="green" /><KpiCard label="Acties vandaag" value={formatNumber(snapshot.kpis.reviewMatches + snapshot.kpis.failedChecks)} helper="Matches en controles vragen aandacht" href="/waarschuwingen" tone="blue" /></section>

    <section className="grid gap-4 xl:grid-cols-[1.6fr_.9fr]"><div className="surface-card p-5"><div className="flex items-center justify-between"><h2 className="text-[15px] font-semibold text-[#24344d]">Prijspositie t.o.v. concurrenten</h2><div className="flex gap-4 text-[9px] text-[#718096]"><span className="text-[#2f6dbb]">● Eigen / laatste prijs</span><span className="text-[#aeb8c7]">● Vorige prijs</span></div></div><div className="mt-6 flex h-[210px] items-end gap-5 border-b border-l border-[#e9edf3] px-5">{(movements.length ? movements : [{productName:'Geen data',competitor:'',previousPrice:0,latestPrice:0,delta:0}]).map((m,i)=>{ const latest=Math.max(Math.abs(m.latestPrice),1); const previous=Math.max(Math.abs(m.previousPrice),1); return <div key={`${m.productName}-${i}`} className="flex min-w-0 flex-1 items-end justify-center gap-1.5"><div className="w-[38%] rounded-t-[2px] bg-[#2f6dbb]" style={{height:`${Math.max(20,latest/maxMove*165)}px`}}/><div className="w-[38%] rounded-t-[2px] bg-[#d5ddea]" style={{height:`${Math.max(14,previous/maxMove*165)}px`}}/></div>})}</div><div className="mt-2 grid text-center text-[9px] text-[#8090a4]" style={{gridTemplateColumns:`repeat(${Math.max(movements.length,1)},minmax(0,1fr))`}}>{(movements.length ? movements : [{productName:'Geen data'}]).map((m,i)=><span key={i} className="truncate px-1">{m.productName}</span>)}</div></div>

      <div className="surface-card p-5"><h2 className="text-[15px] font-semibold text-[#24344d]">Prijsverdeling producten</h2><div className="mt-6 flex items-center gap-6"><div className="relative h-[150px] w-[150px] shrink-0 rounded-full" style={{background:`conic-gradient(#29a56f 0 ${lowPct}%, #ee6769 ${lowPct}% ${lowPct+highPct}%, #f2a51a ${lowPct+highPct}% 100%)`}}><div className="absolute inset-[27px] flex flex-col items-center justify-center rounded-full bg-white"><span className="text-[22px] font-bold text-[#17233a]">{formatNumber(snapshot.kpis.monitoredProducts)}</span><span className="text-[9px] text-[#7c899b]">producten</span></div></div><div className="space-y-3 text-[10px] text-[#44546a]"><p><span className="mr-2 text-[#29a56f]">●</span>Onder / gelijk markt <b className="float-right ml-5">{lowPct}%</b></p><p><span className="mr-2 text-[#ee6769]">●</span>Boven markt <b className="float-right ml-5">{highPct}%</b></p><p><span className="mr-2 text-[#f2a51a]">●</span>Geen prijsdata <b className="float-right ml-5">{missingPct}%</b></p></div></div></div></section>

    <section className="grid gap-4 xl:grid-cols-[1.6fr_.9fr]"><div className="surface-card overflow-hidden"><div className="flex items-center justify-between px-5 py-4"><h2 className="text-[15px] font-semibold text-[#24344d]">Producten die direct aandacht nodig hebben</h2><Link href="/producten" className="text-[10px] font-semibold text-[#3977db]">Bekijk alle →</Link></div><div className="overflow-x-auto"><table className="min-w-full border-0 rounded-none"><thead><tr><th className="px-5 py-3 text-left">Product</th><th className="px-4 py-3 text-left">Concurrent</th><th className="px-4 py-3 text-right">Vorige prijs</th><th className="px-4 py-3 text-right">Laatste prijs</th><th className="px-5 py-3 text-right">Verschil</th></tr></thead><tbody>{attentionRows.length ? attentionRows.map((m,i)=><tr key={i}><td className="px-5 py-3.5 font-semibold text-[#2e3e55]">{m.productName}</td><td className="px-4 py-3.5 text-[#718096]">{m.competitor}</td><td className="px-4 py-3.5 text-right">{formatCurrency(m.previousPrice)}</td><td className="px-4 py-3.5 text-right">{formatCurrency(m.latestPrice)}</td><td className={`px-5 py-3.5 text-right font-semibold ${m.delta>0?'text-[#ee6769]':'text-[#29a56f]'}`}>{m.delta>0?'+':''}{formatCurrency(m.delta)}</td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center text-[11px] text-[#8491a2]">Nog geen prijsbewegingen beschikbaar.</td></tr>}</tbody></table></div></div>

      <div className="surface-card p-5"><div className="flex items-center justify-between"><h2 className="text-[15px] font-semibold text-[#24344d]">Recente prijswijzigingen</h2><Link href="/producten" className="text-[10px] font-semibold text-[#3977db]">Bekijk alle →</Link></div><div className="mt-3 divide-y divide-[#edf0f4]">{movements.slice(0,5).map((m,i)=><div key={i} className="flex items-center gap-3 py-3"><div className={`flex h-7 w-7 items-center justify-center rounded-full ${m.delta>0?'bg-[#fff0f0] text-[#ee6769]':'bg-[#ecf8f2] text-[#29a56f]'}`}>{m.delta>0?'↑':'↓'}</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold text-[#2f3e54]">{m.productName}</p><p className="truncate text-[9px] text-[#8794a6]">{m.competitor}</p></div><p className="text-[10px] font-semibold text-[#2f3e54]">{formatCurrency(m.previousPrice)} → {formatCurrency(m.latestPrice)}</p></div>)}</div></div></section>
  </div>
}
