import { createCompanyAction, switchCompanyAction, updateCompanyStatusAction } from '@/app/actions/adminActions'
import { requireSuperAdmin } from '@/lib/authz'
import { prisma } from '@/lib/prisma'

export default async function OrganisatiesPage() {
  const actor = await requireSuperAdmin()
  const companies = await prisma.company.findMany({
    orderBy: { name: 'asc' },
    include: { _count: { select: { memberships: true, products: true, competitors: true } }, license: { include: { plan: true } } },
  })
  return <div className="space-y-5"><section className="strong-panel p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-[16px] font-bold text-[#202536]">Organisaties</h2><p className="mt-1 text-[11px] leading-5 text-[#778195]">Als super admin kun je meerdere bedrijven beheren en direct van actieve organisatie wisselen.</p></div><span className="rounded-full bg-[var(--blue-soft)] px-3 py-1.5 text-[10px] font-bold text-[var(--blue)]">{companies.length} organisaties</span></div></section>
  <section className="grid gap-4 xl:grid-cols-[360px_1fr]"><form action={createCompanyAction} className="strong-panel p-5"><h3 className="text-[14px] font-bold text-[#252a37]">Nieuw bedrijf aanmaken</h3><div className="mt-4 space-y-3"><input name="name" required minLength={2} placeholder="Bedrijfsnaam" className="toolbar-control w-full" /><input name="billingEmail" type="email" placeholder="Facturatie e mail" className="toolbar-control w-full" /><input name="defaultCurrency" defaultValue="EUR" placeholder="Valuta" className="toolbar-control w-full" /><input name="timezone" defaultValue="Europe/Amsterdam" placeholder="Tijdzone" className="toolbar-control w-full" /></div><button className="primary-action mt-4 w-full">Organisatie aanmaken</button></form>
  <div className="grid gap-3">{companies.map((company) => <div key={company.id} className={`strong-panel p-4 ${company.id === actor.companyId ? 'ring-2 ring-[var(--blue)]/20' : ''}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><p className="text-[13px] font-bold text-[#252a37]">{company.name}</p>{company.id === actor.companyId ? <span className="rounded-full bg-[var(--green-soft)] px-2 py-1 text-[9px] font-bold text-[var(--green)]">Actief</span> : null}</div><p className="mt-1 text-[10px] text-[#8790a2]">{company._count.memberships} gebruikers, {company._count.products} producten, {company._count.competitors} concurrenten, {company.license?.plan.name ?? 'geen plan'}</p></div><div className="flex flex-wrap gap-2">{company.id !== actor.companyId && company.status === 'ACTIVE' ? <form action={switchCompanyAction}><input type="hidden" name="companyId" value={company.id} /><button className="secondary-action">Open bedrijf</button></form> : null}<form action={updateCompanyStatusAction}><input type="hidden" name="companyId" value={company.id} /><input type="hidden" name="status" value={company.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'} /><button className="secondary-action">{company.status === 'ACTIVE' ? 'Deactiveren' : 'Activeren'}</button></form></div></div></div>)}</div></section></div>
}
