export const dynamic = 'force-dynamic'

import Link from 'next/link'
import { MatchStatus } from '@/generated/prisma/client'
import { DataTable } from '@/components/DataTable'
import { StatCard } from '@/components/StatCard'
import { getDashboardSnapshot, type DashboardSnapshot } from '@/lib/dashboard'
import { formatCurrency, formatDate, formatNumber } from '@/lib/format'

function readParam(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value }

const emptySnapshot: DashboardSnapshot = {
  filterOptions: { countries: [], productGroups: [], competitors: [] }, metrics: [],
  kpis: { monitoredProducts: 0, activeOffers: 0, validMatches: 0, reviewMatches: 0, withoutCompetitorPrice: 0, engelsLowest: 0, engelsHigher: 0, averagePriceIndex: null, failedChecks: 0, staleData: 0 },
  biggestIncreases: [], biggestDecreases: [], failedChecks: [], staleOffers: [],
}

function WorkflowCard({ title, subtitle, value, tone, href }: { title: string; subtitle: string; value: string; tone: 'red' | 'blue' | 'green' | 'violet'; href: string }) {
  const styles = { red: 'border-[#ffd3d9] bg-[var(--accent-soft)] text-[var(--accent)]', blue: 'border-[#d9e6ff] bg-[var(--blue-soft)] text-[var(--blue)]', green: 'border-[#d9f0e3] bg-[var(--green-soft)] text-[var(--green)]', violet: 'border-[#e3dcff] bg-[var(--violet-soft)] text-[var(--violet)]' }
  return <Link href={href} className={`group rounded-2xl border p-4 transition-transform hover:-translate-y-0.5 ${styles[tone]}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[13px] font-semibold text-[#252a37]">{title}</p><p className="mt-1 text-[11px] leading-5 text-[#7d8698]">{subtitle}</p></div><span className="rounded-full bg-white/75 px-2.5 py-1 text-[11px] font-semibold">{value}</span></div></Link>
}

export default async function DashboardPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams
  const filters: { countryId?: string; productGroupId?: string; competitorId?: string; matchStatus?: MatchStatus | '' } = { countryId: readParam(params.land), productGroupId: readParam(params.productgroep), competitorId: readParam(params.concurrent), matchStatus: (readParam(params.matchstatus) as MatchStatus | undefined) ?? '' }
  let snapshot = emptySnapshot
  let databaseAvailable = true
  try { snapshot = await getDashboardSnapshot(filters) } catch (error) { console.error('Dashboard database query failed', error); databaseAvailable = false }

  const coverage = snapshot.kpis.monitoredProducts > 0 ? Math.min(100, Math.round((snapshot.kpis.validMatches / snapshot.kpis.monitoredProducts) * 100)) : 0
  const healthyChecks = Math.max(0, snapshot.kpis.activeOffers - snapshot.kpis.failedChecks - snapshot.kpis.staleData)
  const checkHealth = snapshot.kpis.activeOffers > 0 ? Math.max(0, Math.min(100, Math.round((healthyChecks / snapshot.kpis.activeOffers) * 100))) : 0
  const nextActionHref = snapshot.kpis.reviewMatches > 0 ? '/productmatches' : '/prijsstrategie'
  const nextActionTitle = snapshot.kpis.reviewMatches > 0 ? 'Controleer openstaande productmatches' : 'Bekijk prijsadviezen'
  const nextActionMeta = snapshot.kpis.reviewMatches > 0 ? `${snapshot.kpis.reviewMatches} matches vragen aandacht` : 'Gebruik marktdata voor een onderbouwd prijsbesluit'

  return (
    <div className="space-y-5">
      {!databaseAvailable && <div className="rounded-2xl border border-[#ffd2d9] bg-[var(--accent-soft)] p-4 text-sm text-[#b4233d]"><p className="font-semibold">Databaseverbinding mislukt</p><p className="mt-1 text-[12px]">Het dashboard blijft beschikbaar, maar toont geen waarden totdat de verbinding is hersteld.</p></div>}
      <section className="grid gap-4 xl:grid-cols-[1fr_340px]">
        <div className="surface-card px-5 py-5 sm:px-6"><p className="eyebrow">Prijsmonitoring</p><h1 className="mt-2 text-[28px] font-semibold tracking-[-0.035em] text-[#161a26] sm:text-[32px]">Grip op marktprijzen en commerciële ruimte</h1><p className="mt-2 max-w-3xl text-[13px] leading-6 text-[#697386]">Monitor concurrenten, valideer matches, signaleer prijsbewegingen en vertaal marktdata naar concrete prijsbesluiten.</p></div>
        <Link href={nextActionHref} className="surface-card group flex items-center justify-between gap-4 p-5 transition-transform hover:-translate-y-0.5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full border border-[#d8e5ff] bg-[var(--blue-soft)] text-[var(--blue)]"><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m9 6 7 6-7 6V6Z" /></svg></div><div><p className="text-[11px] font-semibold text-[#687184]">Volgende stap</p><p className="mt-1 text-[13px] font-semibold text-[#202536]">{nextActionTitle}</p><p className="mt-0.5 text-[11px] text-[#8a93a5]">{nextActionMeta}</p></div></div><span className="text-lg text-[#2c3343] transition-transform group-hover:translate-x-1">›</span></Link>
      </section>
      <section className="surface-card p-4 sm:p-5">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-[14px] font-semibold text-[#252a37]">Pricing workflow</h2><p className="mt-1 text-[11px] text-[#7d8698]">Van datadekking naar gecontroleerd prijsadvies.</p></div><form className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><select name="land" defaultValue={filters.countryId} className="h-9 rounded-xl border border-[var(--border)] bg-white px-3 text-[11px] text-[#566071]"><option value="">Alle landen</option>{snapshot.filterOptions.countries.map((country) => <option key={country.id} value={country.id}>{country.name}</option>)}</select><select name="productgroep" defaultValue={filters.productGroupId} className="h-9 rounded-xl border border-[var(--border)] bg-white px-3 text-[11px] text-[#566071]"><option value="">Alle productgroepen</option>{snapshot.filterOptions.productGroups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select><select name="concurrent" defaultValue={filters.competitorId} className="h-9 rounded-xl border border-[var(--border)] bg-white px-3 text-[11px] text-[#566071]"><option value="">Alle concurrenten</option>{snapshot.filterOptions.competitors.map((competitor) => <option key={competitor.id} value={competitor.id}>{competitor.name}</option>)}</select><select name="matchstatus" defaultValue={filters.matchStatus} className="h-9 rounded-xl border border-[var(--border)] bg-white px-3 text-[11px] text-[#566071]"><option value="">Alle matchstatussen</option>{Object.values(MatchStatus).map((status) => <option key={status} value={status}>{status}</option>)}</select><button className="focus-ring h-9 rounded-xl border border-[#ffd3d9] bg-[var(--accent-soft)] px-4 text-[11px] font-semibold text-[var(--accent)]">Filters toepassen</button></form></div>
        <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><WorkflowCard title="Monitor" subtitle="Actieve concurrentieaanbiedingen" value={formatNumber(snapshot.kpis.activeOffers)} tone="red" href="/concurrenten" /><WorkflowCard title="Match" subtitle="Geldige productkoppelingen" value={`${coverage}%`} tone="blue" href="/productmatches" /><WorkflowCard title="Analyseer" subtitle="Gemiddelde prijsindex" value={snapshot.kpis.averagePriceIndex ? formatNumber(snapshot.kpis.averagePriceIndex, 1) : '—'} tone="green" href="/producten" /><WorkflowCard title="Adviseer" subtitle="Van marktdata naar prijsbesluit" value="Open" tone="violet" href="/prijsstrategie" /></div>
        <div className="mt-4 flex items-center gap-3 border-t border-[var(--border)] pt-4"><p className="w-32 text-[11px] font-medium text-[#6d7688]">Datadekking</p><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-[#eef0f4]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${coverage}%` }} /></div><p className="w-10 text-right text-[11px] font-semibold text-[#697386]">{coverage}%</p></div>
      </section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Gemonitorde producten" value={formatNumber(snapshot.kpis.monitoredProducts)} helper={`${formatNumber(snapshot.kpis.withoutCompetitorPrice)} zonder bruikbare concurrentieprijs`} tone="red" /><StatCard title="Geldige matches" value={formatNumber(snapshot.kpis.validMatches)} helper={`${formatNumber(snapshot.kpis.reviewMatches)} vragen handmatige controle`} accent={coverage >= 90 ? 'Sterk' : 'Verbeteren'} tone="blue" /><StatCard title="Engels laagste prijs" value={formatNumber(snapshot.kpis.engelsLowest)} helper={`${formatNumber(snapshot.kpis.engelsHigher)} producten liggen boven de laagste marktprijs`} tone="green" /><StatCard title="Controlekwaliteit" value={`${checkHealth}%`} helper={`${formatNumber(snapshot.kpis.failedChecks)} mislukt, ${formatNumber(snapshot.kpis.staleData)} verouderd`} accent={checkHealth >= 90 ? 'Gezond' : 'Aandacht'} tone="amber" /></section>
      <section className="grid gap-4 xl:grid-cols-2">
        <div className="surface-card p-4 sm:p-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-[14px] font-semibold text-[#252a37]">Grootste prijsstijgingen</h2><p className="mt-1 text-[11px] text-[#8a93a5]">Recente bewegingen bij gematchte concurrenten.</p></div><Link href="/producten" className="text-[11px] font-semibold text-[var(--blue)]">Bekijk producten</Link></div><DataTable columns={[{ key: 'product', header: 'Product' }, { key: 'concurrent', header: 'Concurrent' }, { key: 'van', header: 'Van' }, { key: 'naar', header: 'Naar' }, { key: 'delta', header: 'Verschil' }]} rows={snapshot.biggestIncreases.map((item) => ({ product: item.productName, concurrent: item.competitor, van: formatCurrency(item.previousPrice), naar: formatCurrency(item.latestPrice), delta: formatCurrency(item.delta) }))} /></div>
        <div className="surface-card p-4 sm:p-5"><div className="mb-3"><h2 className="text-[14px] font-semibold text-[#252a37]">Grootste prijsdalingen</h2><p className="mt-1 text-[11px] text-[#8a93a5]">Prijsdruk die mogelijk om een besluit vraagt.</p></div><DataTable columns={[{ key: 'product', header: 'Product' }, { key: 'concurrent', header: 'Concurrent' }, { key: 'van', header: 'Van' }, { key: 'naar', header: 'Naar' }, { key: 'delta', header: 'Verschil' }]} rows={snapshot.biggestDecreases.map((item) => ({ product: item.productName, concurrent: item.competitor, van: formatCurrency(item.previousPrice), naar: formatCurrency(item.latestPrice), delta: formatCurrency(item.delta) }))} /></div>
      </section>
      <section className="grid gap-4 xl:grid-cols-2">
        <div className="surface-card p-4 sm:p-5"><div className="mb-3"><h2 className="text-[14px] font-semibold text-[#252a37]">Mislukte prijscontroles</h2><p className="mt-1 text-[11px] text-[#8a93a5]">Bronnen die technisch aandacht nodig hebben.</p></div><DataTable columns={[{ key: 'concurrent', header: 'Concurrent' }, { key: 'product', header: 'Product' }, { key: 'melding', header: 'Melding' }, { key: 'tijd', header: 'Gecontroleerd' }]} rows={snapshot.failedChecks.map((check) => ({ concurrent: check.competitorOffer.competitor.name, product: check.competitorOffer.productMatch?.product.name ?? 'Ongekoppeld', melding: check.errorMessage ?? 'Onbekende fout', tijd: formatDate(check.checkedAt) }))} /></div>
        <div className="surface-card p-4 sm:p-5"><div className="mb-3"><h2 className="text-[14px] font-semibold text-[#252a37]">Verouderde prijsgegevens</h2><p className="mt-1 text-[11px] text-[#8a93a5]">Aanbiedingen waarvan de laatste geldige controle te oud is.</p></div><DataTable columns={[{ key: 'concurrent', header: 'Concurrent' }, { key: 'product', header: 'Product' }, { key: 'prijs', header: 'Prijs' }, { key: 'laatsteControle', header: 'Laatste controle' }]} rows={snapshot.staleOffers.map((offer) => ({ concurrent: offer.competitor.name, product: offer.productMatch?.product.name ?? 'Ongekoppeld', prijs: formatCurrency(offer.normalizedPrice), laatsteControle: formatDate(offer.lastCheckedAt) }))} /></div>
      </section>
    </div>
  )
}
